### ISSUE TITLE
Operation Could not be completed

### ISSUE THREAD

**Issue by geanes** [iluvcapra/ProToolsText#1]
Type (choose one): Defect / Feature Request / Cosmetic / Documentation / Community Issue / Other

### Description:

The operation couldn't be completed. PKit.PTTextFileParser.(ParseTokenError in _271CE7F113D4D6E2569597C0A770D29A) error 1.)

### Steps to Reproduce:
1. Open PText Convert
2. File: Convert Text Export...
3. Choose text file exported from Pro Tools 12.8.2
4. Error is reported in a pop-up.

### Expected Result:
 Should generate a .csv file.

### Actual Result:
Error pops up and prevents usage.
---

Release: 0.2

Commit (if available):

Severity (choose one): "Can't work without it."

**Comment by iluvcapra** [comment]
Hey boss, can you attach the text export from Pro Tools you used?

**Comment by iluvcapra** [comment]
I've added some better error reporting so at least you should get a sensible error message, but otherwise I can't reproduce this error. Please include the text file you're trying to import.

**Comment by geanes** [comment]
Hi, Jamie.

Attached is an example output from pro tools that gives me the error.

BTW, I am Susan Fitz-Simon’s foley mixer here in Austin, TX. She speaks highly of you! We miss Agent Orange.

[cue test utf8.txt](https://github.com/iluvcapra/ProToolsText/files/1648359/cue.test.utf8.txt)

**Comment by iluvcapra** [comment]
Can you please attach this file as a text file?

**Comment by geanes** [comment]
Updated my previous comment to include file.

**Comment by iluvcapra** [comment]
Yeah it seems like there's something peculiar about how inactive tracks are printed. For now you can just activate the track and it should be okay but I'll look at this.

**Comment by geanes** [comment]
Good to know. Thank you. 

Glenn

**Comment by iluvcapra** [comment]
This fix is in release v0.2.1
